spring.application.name=chargeProxy
server.port=8082

# Asaas Configuration
asaas.url=https://sandbox.asaas.com
asaas.key=${ASAAS_SANDBOX_API_KEY:}
asaas.webhook.token=${ASAAS_WEBHOOK_TOKEN:}

# Manager SOAP Configuration (for webhook callbacks)
manager.wsdl.url=http://charge-manager:8090/ws/webhook?wsdl

# Feign logging
logging.level.br.edu.ifpb.dac.chargeProxy.infra.integration.asaas.AsaasClient=DEBUG